export const NIGERIA_36_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

// Common cities/major towns per state.
// (Practical, not exhaustive.)
export const STATE_TO_CITIES: Record<string, readonly string[]> = {
  "Abia": ["Aba", "Umuahia", "Ohafia", "Bende"],
  "Adamawa": ["Yola", "Mubi", "Numan", "Jimeta"],
  "Akwa Ibom": ["Uyo", "Ikot Ekpene", "Eket", "Abak"],
  "Anambra": ["Awka", "Onitsha", "Nnewi", "Ogbaru"],
  "Bauchi": ["Bauchi", "Dass", "Toro", "Ningi"],
  "Bayelsa": ["Yenagoa", "Brass", "Ogbia", "Kolo"],
  "Benue": ["Makurdi", "Gboko", "Katsina-Ala", "Otukpo"],
  "Borno": ["Maiduguri", "Biu", "Monguno", "Gwoza"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Obubra"],
  "Delta": ["Warri", "Asaba", "Sapele", "Ughelli"],
  "Ebonyi": ["Abakaliki", "Afikpo", "Ezza", "Onicha"],
  "Edo": ["Benin City", "Auchi", "Ekpoma", "Sapele"],
  "Ekiti": ["Ado-Ekiti", "Ilawe", "Ikere", "Ode"],
  "Enugu": ["Enugu", "Nsukka", "Oji River", "Ezeagu"],
  "FCT - Abuja": [
    "Abuja",
    "Central Business District (CBD)",
    "Garki Area 1",
    "Garki Area 2",
    "Garki Area 3",
    "Garki Area 7",
    "Garki Area 8",
    "Garki Area 10",
    "Garki Area 11",
    "Wuse Zone 1",
    "Wuse Zone 2",
    "Wuse Zone 3",
    "Wuse Zone 4",
    "Wuse Zone 5",
    "Wuse Zone 6",
    "Wuse Zone 7",
    "Maitama District",
    "Maitama 2 (Extension)",
    "Asokoro District",
    "Asokoro Extension",
    "Gwarinpa Estate (1st — 5th Avenue)",
    "Gwarinpa 2",
    "Lokogoma District",
    "Lokogoma Phase 1",
    "Lokogoma Phase 2",
    "Lugbe District",
    "Lugbe Extension",
    "Chika",
    "Chukuku",
    "Pyakasa",
    "Kubwa Phase 1–5",
    "Byazhin",
    "Goba",
    "Dutse",
    "Bwari Town",
    "Ushafa",
    "Byui",
    "Igu",
    "Kawu",
    "Kuje Town",
    "Chibiri",
    "Gwargwada",
    "Rubochi",
    "Wako",
    "Gwagwalada Town",
    "Dobi",
    "Paiko Road",
    "Staff Quarters",
    "Abaji Town",
    "Yaba",
    "Rimba",
    "Kwali Town",
    "Pai",
    "Kilankwa",
    "Apo District",
    "Apo Resettlement",
    "Durumi",
    "Gudu",
    "Kado",
    "Kabusa",
    "Katampe",
    "Katampe Extension",
    "Life Camp",
    "Mbora",
    "Mpape",
    "Nbora",
    "Nnewi",
    "Nyanya",
    "Karu",
    "Orozo",
    "Galadimawa",
    "Utako",
    "Jabi",
    "Jahi",
    "Karmo",
    "Wuye",
    "Mabushi",
    "Dakibiyu",
    "Dakwo",
    "Gaduwa",
    "Godab Estate",
    "Citec Estate",
    "Sunnyvale Estate",
    "Efab Estate (multiple locations)",
    "Treasure Estate",
  ],

  "Gombe": ["Gombe", "Dukku", "Kaltungo", "Billiri"],
  "Imo": ["Owerri", "Okigwe", "Orlu", "Mbaise"],
  "Jigawa": ["Dutse", "Hadejia", "Kafin Hausa", "Ringim"],
  "Kaduna": ["Kaduna", "Zaria", "Kafanchan", "Kachia"],
  "Kano": ["Kano", "Kumbotso", "Wudil", "Dawakin Kudu"],
  "Katsina": ["Katsina", "Daura", "Dutsin-Ma", "Kankara"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Dandi", "Zuru"],
  "Kogi": ["Lokoja", "Koton Karfe", "Okene", "Mopa Muro"],
  "Kwara": ["Ilorin", "Offa", "Omu-Aran", "Baro"],
  "Lagos": ["Lagos", "Ikeja", "Victoria Island", "Epe"],
  "Nasarawa": ["Lafia", "Keffi", "Akwanga", "Wamba"],
  "Niger": ["Minna", "Kontagora", "Bida", "Suleja"],
  "Ogun": ["Abeokuta", "Ikenne", "Sagamu", "Ota"],
  "Ondo": ["Akure", "Ondo", "Ado-Owa", "Okitipupa"],
  "Osun": ["Osogbo", "Iwo", "Ogbomoso", "Ejigbo"],
  "Oyo": ["Ibadan", "Oyo", "Saki", "Ogbomoso"],
  "Plateau": ["Jos", "Bukuru", "Pankshin", "Vom"],
  "Rivers": ["Port Harcourt", "Bori", "Obio-Akpor", "Degema"],
  "Sokoto": ["Sokoto", "Gusau", "Kebbe", "Wurno"],
  "Taraba": ["Jalingo", "Gassol", "Sardauna", "Wukari"],
  "Yobe": ["Damaturu", "Potiskum", "Fika", "Nguru"],
  "Zamfara": ["Gusau", "Zaria", "Kaura Namoda", "Maradun"],
};

